import { Inter } from "next/font/google";
import "./globals.css";
import "../styles/main.scss"
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import Steps from "@/components/Steps";
import InvoiceCTA from "@/components/InvoiceCTA";
import InvoiceTemplates from "@/components/InvoiceTemplates";
import Features from "@/components/Features";
import Pricing from "@/components/Pricing";
import FAQ from "@/components/FAQ";
import AppFooter from "@/components/AppFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Hero />
        <Steps />
        <InvoiceCTA />
        <InvoiceTemplates />
        <Features />
        <Pricing />
        <FAQ />
        {children}
        <AppFooter />
      </body>
    </html>
  );
}
